apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qvihqv3tk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qvihqv3tk-nodejs 
  name: qvihqv3tk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qvihqv3tk-nodejs 
