apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qvihqv3tk-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-25ac36231b.pa2z.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:c4e8e1cb93f787bd55accd44780729216b44030e@sha256:777b79457fc2c14e696fb10d9473248912b34fe666178355cfc4af510b6cdf7a
          name: container-image
